Repository CrimsonWarpedcraft/MobActions, pull requests merged in 2021-01, with the labels that each got.

#41 action mobs cant attack players now
  src/main/java/com/snowypeaksystems/mobactions/listener/EventListener.java
Labels: enhancement

#44 Better data checks and throw exceptions when corruption is detected
  src/main/java/com/snowypeaksystems/mobactions/IMobActions.java
  src/main/java/com/snowypeaksystems/mobactions/InteractiveMob.java
  src/main/java/com/snowypeaksystems/mobactions/MobActions.java
  src/main/java/com/snowypeaksystems/mobactions/data/CommandData.java
  src/main/java/com/snowypeaksystems/mobactions/data/IncompleteDataException.java
  src/main/java/com/snowypeaksystems/mobactions/data/WarpData.java
  src/main/java/com/snowypeaksystems/mobactions/listener/EventListener.java
  src/main/java/com/snowypeaksystems/mobactions/util/Messages.java
Labels: enhancement

#45 Command refactor
  README.md
  src/main/java/com/snowypeaksystems/mobactions/actions/CommandAction.java
  src/main/java/com/snowypeaksystems/mobactions/data/CommandData.java
  src/main/java/com/snowypeaksystems/mobactions/data/ICommandData.java
  src/main/java/com/snowypeaksystems/mobactions/data/IWarpData.java
  src/main/java/com/snowypeaksystems/mobactions/data/MobData.java
  src/main/java/com/snowypeaksystems/mobactions/listener/CommandListener.java
  src/main/java/com/snowypeaksystems/mobactions/player/ConsoleUser.java
  src/main/java/com/snowypeaksystems/mobactions/player/MobActionsPlayer.java
  src/main/java/com/snowypeaksystems/mobactions/player/MobActionsUser.java
  src/main/resources/plugin.yml
  src/test/java/com/snowypeaksystems/mobactions/data/command/CommandDataTest.java
  src/test/java/com/snowypeaksystems/mobactions/player/ConsoleUserTest.java
  src/test/java/com/snowypeaksystems/mobactions/player/MobActionsPlayerTest.java
  src/test/java/com/snowypeaksystems/mobactions/player/StatusTest.java
Labels: Passed Manual Testing, enhancement

#49 readme and help message re-wording
  README.md
  src/main/java/com/snowypeaksystems/mobactions/listener/CommandListener.java
  src/main/java/com/snowypeaksystems/mobactions/util/Messages.java
Labels: documentation, enhancement
